### ISSUE TITLE
Add the possibility to unsave what's been downloaded ?

### ISSUE THREAD

**Issue by NebNimaj** [makuto/redditLikedSavedImageDownloader#11]
Hi, first of all, thank you for this project !
I was thinking, maybe you could add an option to unsave what's been downloaded ? Might help for those like me that have HUGE collection of saved post and want to clean this up
If it's impossible or complicated to achieve, then no worry, it's just a suggestion

Again, thank you for your work !

**Comment by makuto** [comment]
No problem, I'm glad you've found it useful!

I'll look into the unsave feature soon. It could be relatively easy if the
APIs support it, but I'd have to check to know for sure.

On Feb 18, 2018 3:43 AM, "NebNimaj" <notifications@github.com> wrote:

Hi, first of all, thank you for this project !
I was thinking, maybe you could add an option to unsave what's been
downloaded ? Might help for those like me that have HUGE collection of
saved post and want to clean this up
If it's impossible or complicated to achieve, then no worry, it's just a
suggestion

Again, thank you for your work !

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/makuto/redditLikedSavedImageDownloader/issues/11>, or mute
the thread

**Comment by sn0wyfall** [comment]
Hey! I just wanted to comment here to say that this would be really useful. I currently have to unsaved everything manually (which is a real pain!). It would be great to have this feature!

**Comment by makuto** [comment]
I added this feature in fe884818dee22351afddc9cf28ec712be7b153a2. 

You can turn it on by adding `Reddit_Unlike_Liked=True` and/or `Reddit_Unsave_Saved=True` to your settings.txt.

You can also toggle these settings using the web server interface. Have either of you checked it out? I would love to hear your feedback. Create a new issue if you have problems using the web interface.

**Comment by makuto** [comment]
Note that if you want to unsave all of your posts you'll need to up your Reddit_Total_requests to a value high enough to include all posts, or run the script multiple times.

You may also need to set Reddit_Try_Request_Only_New to False in order for the script to not early out (it does this because it knows you've already downloaded the submission, so it won't try to get older submissions).

If you only care about unsaving things, set Reddit_Save_Liked to False to save time and requests.

**Comment by sn0wyfall** [comment]
You crazy person.

I will test this out as soon as I can, and then get back to you!
