### ISSUE TITLE
Titles get truncated

### ISSUE THREAD

**Issue by sn0wyfall** [makuto/redditLikedSavedImageDownloader#7]
Firstly, I tried using [`redditcurl`](https://pypi.python.org/pypi/redditcurl/2.1.1) and ran into a million problems. I tried using this script and ran into a bunch of problems as well, but managed to fix it. It actually works, so right now I'm *absolutely* stoked. Thanks a lot!

So, I'm experiencing a problem. When I save images, they save with filenames like this:

    The prettiest place Ive ever seen Joffre Lake_1825000257

However, technically the title should be:

    The prettiest place I've ever seen. Joffre Lakes Provincial Park, British Columbia [OC] [2757x3446]

I'm not sure why no one pointed this out yet – which leads me to believe that this must be a problem just with me. I might be wrong though, so I'd love some suggestions!

Also, I got this image from r/EarthPorn. Now, the folder for the subreddit inside the output folder is called:

    EarthPorn Amazing images of light and landsca

I'd like it to be named just the subreddit, like so:

    EarthPorn

Is there a way to do this?

In any case, thanks _so much_ for making this. This is just awesome, and I'm glad that after hours and hours of searching I finally found something that I had wanted for such a long time. You rock!

**Comment by makuto** [comment]
Thanks for the compliments!

Yes, I can make the changes you've requested. It should only take me a couple minutes. I'll do it right now.

**Comment by makuto** [comment]
a22a7840f0fc67298487317d2d41d2f69ca81b6d addresses the problems you've had. `git pull` and let me know if that works for you.

 It turns out I already wrote the subreddit folder names code, I just made a mistake :). Titles are now truncated to 250 characters instead of 45, which was a completely arbitrary value. 255 is the max filename length on most filesystems.

**Comment by sn0wyfall** [comment]
Wow, thanks for the quick reply! I tried modifying the files and it works perfectly! Amazing!!!

I'm not sure if you're aware of it, but the only problem I see now is that the characters `[` and `]` don't seem to appear. Not a huge deal so if that'd be hard to fix I don't mind.

Also, what about the numbers which appear after every filename? Let's think about that. The normal post names seem to end in `_-000000000` or `_000000000`, where the `000...` string isn't a constant length, meaning that I wouldn't be able to automatically remove the last x characters from the file name. Again, not a huge deal, but if it's easy to fix I'd appreciate it if you could tell me how (sorry, I could probably figure it out myself by looking at the code, but I don't know much python!)

**Comment by sn0wyfall** [comment]
Honestly I feel bad complaining about these other issues after you fixed all the other problems I was complaining about. Feel free to ignore them if you want – what you did is more than what I was expecting! And it works really well in any case, so I don't have much chance to complain!

**Comment by makuto** [comment]
The numbers at the end of every filename are a CRC of the URL from which the image was retrieved. The reason why these exist is because posts can have titles which are identical, but we need unique filenames. Subreddits like [/r/CatsStandingUp/](https://www.reddit.com/r/CatsStandingUp/) and [/r/meirl](https://www.reddit.com/r/meirl/) are especially problematic because all posts have nearly identical titles. The number guarantees unique filenames.

If you don't think this is a problem you'll encounter (i.e. you don't think any posts will have identical titles), you can make a few modifications to remove it. 
Change imageSaver.py:411 and 412 to this:
```python
saveFilePath = (unicode(outputDir, errors='replace') + u'/' + subredditDir + u'/' 
                    + safeFileName(submissionTitle) + u'.' + fileType)
```
You can do the same thing for Imgur albums if you care about them:
```python
            saveAlbumPath = (outputDir + u'/' + subredditDir + u'/' 
                + safeFileName(albumTitle))
```

**Comment by makuto** [comment]
Oh, and the `[` and `]` issue: I remove all characters which aren't alphanumeric from filenames. I did it in a super aggressive way because I was paranoid that weird filenames would confuse the filesystem. You can add characters you care about individually to imageSaver.py:167, e.g.:
`acceptableChars = ['_', ' ', '[', ']']`
or remove the sanitization and get the exact title by commenting out (`'''` is python multiline comment) or deleting lines 174 through 176. Replace those lines with `safeName = filename`.

Let me know if this is too difficult for you and I'll prepare a version of the file with your requests :)

**Comment by sn0wyfall** [comment]
Whewwww!!! Finally got the chance to take a look at it, and it works absolutely fine! I don't want to say thanks too much because it's just going to sound overused, but I really appreciate it. This is honestly as perfect as it gets, in my opinion. This (relatively) small script gets done exactly what I need – and a lot more than I wanted that I didn't even know I wanted. I wasn't expecting to find something which actually would save the images to subreddit-specific folders – but having that option would make everything so much more organized, and give me peace of mind that I can save things from other subreddit without having to weed them out manually. And the JSON list with the failed attempts – magnificent! I don't have to worry about any failures and can manually save anything which didn't work! Great work. This is just about perfect, and you absolutely rock!
